# Generated by Django 5.0.4 on 2024-04-24 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'ordering': ['child_name']},
        ),
        migrations.RenameField(
            model_name='child',
            old_name='parent',
            new_name='user_id',
        ),
    ]
