# Generated by Django 5.0.4 on 2024-04-24 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('family', '0002_childtasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childtasks',
            name='child_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='childtasks',
            name='important_dates',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
