# Generated by Django 5.0.4 on 2024-04-23 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_alter_child_birth_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='child',
            unique_together=set(),
        ),
    ]
