# Generated by Django 5.0.4 on 2024-04-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_alter_child_options_rename_parent_child_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='birth_date',
            field=models.DateField(auto_now=True),
        ),
    ]
