# Generated by Django 5.0.4 on 2024-04-24 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_alter_child_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='user_id',
            new_name='user',
        ),
    ]
