# Generated by Django 5.0.4 on 2024-04-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0006_alter_bins_next_collection_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bins',
            name='frequency',
            field=models.CharField(choices=[('week', 'Week'), ('fortnight', 'Fortnight')], max_length=20),
        ),
    ]
