# Generated by Django 5.0.4 on 2024-04-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0007_alter_bins_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='bins',
            name='bins_next_collected',
            field=models.ManyToManyField(blank=True, related_name='collected_next_bins', to='household.bin'),
        ),
    ]
